### Registration

POST http://localhost:4600/user/register
Content-Type: application/json

{
    "name":"Lead",
    "password":"abc",
    "role":"Leader"
}

### login
POST http://localhost:4600/user/login
Content-Type: application/json

{
    "name":"Lead",
    "password":"abc"
}

### Get all Projects
GET http://localhost:4600/leader
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTMzYjJiMGQ4NzQ1ZGU4ZTQ1NzE0ZiIsIm5hbWUiOiJMZWFkIiwiaWF0IjoxNzM3NzAyMTk1fQ.z_g_D1NWIfnESkXzGAXqG22lXTtfffFsqQjpTdFYK4M
Curr_User_Name: Lead